name: from_ui_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  shared_preferences: ^0.5.6+2
  intl: ^0.16.0




  cupertino_icons: ^1.0.1
  introduction_screen: ^1.0.7
  local_auth: ^0.6.3+4
  firebase_core: ^0.5.3
  cloud_functions: ^0.6.0
  firebase_auth: ^0.18.3
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.12.0
  bottom_navy_bar: ^5.6.0
  splash_screen_view: ^1.0.1
  provider: ^4.3.3
  firebase_messaging: ^7.0.0
  http: any
  carousel_slider: any
  adobe_xd: any
  animations: any
  google_fonts: any
  smooth_page_indicator: any
  image_picker: any



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/
    - assets/categories/
    - assets/images/
    - lib/lang/en.json
    - lib/lang/fa.json
    - lib/lang/ar.json
    - lib/lang/hi.json

  fonts:
    - family: Oswald-VariableFont_wght.ttf
      fonts:
      - asset: assets/Fonts/Oswald-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
